### ISSUE TITLE
'Camera' object error

### ISSUE THREAD

**Issue by delenius** [abizovnuralem/go2_omniverse#15]
We get this error on startup (it still loads and seems to work ok).
```
AttributeError: 'Camera' object has no attribute '_rep_registry'
Exception ignored in: <function Camera.__del__ at 0x7f0454780ca0>
Traceback (most recent call last):
  File "/home/ubuntu/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sensors/camera/camera.py", line 139, in __del__
    for _, annotators in self._rep_registry.items():
AttributeError: 'Camera' object has no attribute '_rep_registry'
```

**Comment by delenius** [comment]
We managed to install isaacsim using the normal (omniverse client) method. This changes the errors to this:
```
Summary: 1 package finished [1.09s]
Traceback (most recent call last):
  File "/home/ubuntu/go2_omniverse/main.py", line 25, in <module>
    from omniverse_sim import run_sim
  File "/home/ubuntu/go2_omniverse/omniverse_sim.py", line 7, in <module>
    from omni.isaac.lab.app import AppLauncher
  File "/home/ubuntu/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/app/__init__.py", line 15, in <module>
    from .app_launcher import AppLauncher  # noqa: F401, F403
  File "/home/ubuntu/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/app/app_launcher.py", line 27, in <module>
    from omni.isaac.kit import SimulationApp
ModuleNotFoundError: No module named 'omni.isaac.kit'
```

**Comment by abizovnuralem** [comment]
Thanks for the report! I know this issue, don't have time to fix it.

**Comment by ahanjaya** [comment]
Face the same issue.

**Comment by advaitjawaji** [comment]
Running into the same issue mentioned by @ahanjaya

**Comment by abizovnuralem** [comment]
> system is freezing

What hardware are you using? Can you try one more time with --robot_amount 1 param, please?

**Comment by abizovnuralem** [comment]
I will close this issue, if you have the same errors just open a new one, thanks! Also, use --robot_amount 1 if you have a weak PC hardware setup.

**Comment by haonan-duan** [comment]
I still face the same issue with "AttributeError: 'Camera' object has no attribute '_rep_registry'" is added_copter branch.
