### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by paramoza999** [abizovnuralem/go2_omniverse#18]
/run_sim.sh 
#All required rosdeps installed successfully
Starting >>> carter_navigation
Starting >>> custom_message
Starting >>> isaac_ros2_messages
Starting >>> isaac_ros_navigation_goal
Starting >>> isaac_tutorials
Finished <<< carter_navigation [0.23s]                                  
Finished <<< isaac_tutorials [0.23s]
Finished <<< isaac_ros2_messages [0.31s]                             
Finished <<< custom_message [0.32s]
Finished <<< isaac_ros_navigation_goal [0.53s]          

Summary: 5 packages finished [0.68s]
#All required rosdeps installed successfully
Starting >>> go2_interfaces
Finished <<< go2_interfaces [0.35s]                     

Summary: 1 package finished [0.49s]
[INFO][AppLauncher]: Loading experience file: /home/param/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/app/../../../../../../apps/isaaclab.python.kit
[Warning] [omni.isaac.kit.simulation_app] Modules: ['omniverse_sim', 'omni.kit_app'] were loaded before SimulationApp was started and might not be loaded correctly.
[Warning] [omni.isaac.kit.simulation_app] Please check to make sure no extra omniverse or pxr modules are imported before the call to SimulationApp(...)
Starting kit application with the following args:  ['/home/param/anaconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/exts/omni.isaac.kit/omni/isaac/kit/simulation_app.py', '/home/param/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/app/../../../../../../apps/isaaclab.python.kit', '--/app/tokens/exe-path=/home/param/anaconda3/envs/isaaclab/lib/python3.10/site-packages/omni', '--/persistent/app/viewport/displayOptions=3094', '--/rtx/materialDb/syncLoads=True', '--/rtx/hydra/materialSyncLoads=True', '--/omni.kit.plugin/syncUsdLoads=True', '--/app/renderer/resolution/width=1280', '--/app/renderer/resolution/height=720', '--/app/window/width=1440', '--/app/window/height=900', '--/renderer/multiGpu/enabled=True', '--/app/fastShutdown=True', '--ext-folder', '/home/param/anaconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/exts', '--ext-folder', '/home/param/anaconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/apps', '--/renderer/activeGpu=0', '--/physics/cudaDevice=0', '--portable', '--/app/window/hideUi=False']
Passing the following args to the base kit application:  ['--robot_amount', '2', '--robot', 'go2']
Loading user config located at: '/home/param/anaconda3/envs/isaaclab/lib/python3.10/site-packages/omni/data/Kit/Isaac-Sim/4.0/user.config.json'
[Info] [carb] Logging to file: /home/param/anaconda3/envs/isaaclab/lib/python3.10/site-packages/omni/logs/Kit/Isaac-Sim/4.0/kit_20240707_163211.log
2024-07-07 23:32:11 [0ms] [Warning] [omni.kit.app.plugin] No crash reporter present, dumps uploading isn't available.
[0.035s] [ext: omni.kit.async_engine-0.0.0] startup
[0.102s] [ext: omni.stats-0.0.0] startup
[0.103s] [ext: omni.client-1.1.0] startup
[0.122s] [ext: omni.datastore-0.0.0] startup
[0.123s] [ext: omni.blobkey-1.1.0] startup
[0.123s] [ext: omni.ujitso.default-1.0.0] startup
[0.123s] [ext: omni.hsscclient-0.0.0] startup
[0.124s] [ext: omni.rtx.shadercache.vulkan-1.0.0] startup
[0.124s] [ext: omni.assets.plugins-0.0.0] startup
[0.125s] [ext: omni.gpu_foundation-0.0.0] startup
[0.132s] [ext: carb.windowing.plugins-1.0.0] startup
[0.137s] [ext: omni.kit.renderer.init-0.0.0] startup
2024-07-07 23:32:11 [216ms] [Warning] [gpu.foundation.plugin] Skipping unsupported non-NVIDIA GPU: Intel(R) Graphics (RPL-S)
2024-07-07 23:32:11 [216ms] [Warning] [gpu.foundation.plugin] Skipping unsupported non-NVIDIA GPU: Intel(R) Graphics (RPL-S)

|---------------------------------------------------------------------------------------------|
| Driver Version: 545.29.06     | Graphics API: Vulkan
|=============================================================================================|
| GPU | Name                             | Active | LDA | GPU Memory | Vendor-ID | LUID       |
|     |                                  |        |     |            | Device-ID | UUID       |
|     |                                  |        |     |            | Bus-ID    |            |
|---------------------------------------------------------------------------------------------|
| 0   | NVIDIA GeForce RTX 4080 Laptop.. | Yes: 0 |     | 12282   MB | 10de      | 0          |
|     |                                  |        |     |            | 27e0      | 63ac250e.. |
|     |                                  |        |     |            | 1         |            |
|---------------------------------------------------------------------------------------------|
| 1   | Intel(R) Graphics (RPL-S)        |        |     | 48020   MB | 8086      | 0          |
|     |                                  |        |     |            | a788      | 868088a7.. |
|     |                                  |        |     |            | 0         |            |
|=============================================================================================|
| OS: 22.04.4 LTS (Jammy Jellyfish) ubuntu, Version: 22.04.4, Kernel: 6.5.0-41-generic
| XServer Vendor: The X.Org Foundation, XServer Version: 12101004 (1.21.1.4)
| Processor: 13th Gen Intel(R) Core(TM) i9-13900HX | Cores: 24 | Logical: 48
|---------------------------------------------------------------------------------------------|
| Total Memory (MB): 64026 | Free Memory: 56704
| Total Page/Swap (MB): 0 | Free Page/Swap: 0
|---------------------------------------------------------------------------------------------|
2024-07-07 23:32:11 [409ms] [Warning] [gpu.foundation.plugin] IOMMU is enabled.
[0.522s] [ext: omni.kit.pipapi-0.0.0] startup
[0.523s] [ext: omni.kit.pip_archive-0.0.0] startup
[0.523s] [ext: omni.mtlx-0.1.0] startup
[0.523s] [ext: omni.usd.config-1.0.3] startup
[0.525s] [ext: omni.gpucompute.plugins-0.0.0] startup
[0.525s] [ext: omni.usd.libs-1.0.0] startup
[0.582s] [ext: omni.kit.telemetry-0.5.0] startup
[0.597s] [ext: omni.kit.loop-isaac-1.2.0] startup
[0.598s] [ext: omni.kit.test-0.0.0] startup
[0.631s] [ext: omni.appwindow-1.1.8] startup
[0.670s] [ext: omni.kit.renderer.core-1.0.1] startup
[0.811s] [ext: omni.kit.renderer.capture-0.0.0] startup
[0.812s] [ext: omni.kit.renderer.imgui-1.0.1] startup
[0.879s] [ext: omni.ui-2.23.11] startup
[0.886s] [ext: omni.kit.mainwindow-1.0.3] startup
[0.887s] [ext: carb.audio-0.1.0] startup
[0.889s] [ext: omni.uiaudio-1.0.0] startup
[0.890s] [ext: omni.kit.uiapp-0.0.0] startup
[0.890s] [ext: omni.usd.schema.anim-0.0.0] startup
[0.970s] [ext: omni.usd.schema.audio-0.0.0] startup
[0.973s] [ext: omni.usd.schema.omnigraph-1.0.0] startup
[0.978s] [ext: omni.usd.schema.semantics-0.0.0] startup
[0.980s] [ext: omni.usd.schema.isaac-2.0.2] startup
[0.985s] [ext: omni.usd.schema.physx-106.0.16] startup
[1.015s] [ext: omni.usd.schema.forcefield-106.0.16] startup
[1.020s] [ext: omni.usd.schema.geospatial-0.0.0] startup
[1.022s] [ext: omni.usd.schema.scene.visualization-2.0.2] startup
[1.023s] [ext: omni.kit.window.popup_dialog-2.0.24] startup
[1.025s] [ext: omni.graph.exec-0.9.3] startup
[1.026s] [ext: omni.usd_resolver-1.0.0] startup
[1.030s] [ext: omni.resourcemonitor-105.0.1] startup
[1.031s] [ext: omni.activity.core-1.0.1] startup
[1.032s] [ext: omni.kit.usd_undo-0.1.8] startup
[1.032s] [ext: omni.usd.core-1.2.11] startup
[1.036s] [ext: omni.kit.widget.nucleus_connector-1.1.5] startup
[1.037s] [ext: omni.kit.exec.core-0.13.0] startup
[1.038s] [ext: omni.ujitso.processor.texture-1.0.0] startup
[1.039s] [ext: omni.iray.libs-0.0.0] startup
[1.043s] [ext: usdrt.scenegraph-7.4.8] startup
[1.075s] [ext: omni.ujitso.client-0.0.0] startup
[1.076s] [ext: omni.mdl.neuraylib-0.2.4] startup
[1.077s] [ext: omni.kit.actions.core-1.0.0] startup
[1.078s] [ext: omni.hydra.usdrt_delegate-7.4.7] startup
[1.095s] [ext: omni.timeline-1.0.10] startup
[1.097s] [ext: omni.kit.commands-1.4.9] startup
[1.099s] [ext: omni.kit.audiodeviceenum-1.0.1] startup
[1.100s] [ext: omni.hydra.scene_delegate-0.3.3] startup
[1.106s] [ext: omni.volume-0.5.0] startup
[1.108s] [ext: omni.usd-1.10.39] startup
[1.137s] [ext: omni.hydra.rtx-0.2.0] startup
[1.149s] [ext: omni.kit.hydra_texture-1.2.6] startup
[1.153s] [ext: omni.kit.widget.options_menu-1.1.4] startup
[1.155s] [ext: omni.kit.widget.viewport-106.0.2] startup
[1.157s] [ext: omni.kit.widget.options_button-1.0.2] startup
[1.157s] [ext: omni.kit.window.drop_support-1.0.1] startup
[1.158s] [ext: omni.ui.scene-1.9.3] startup
[1.161s] [ext: omni.kit.viewport.registry-104.0.6] startup
[1.161s] [ext: omni.kit.widget.nucleus_info-1.0.2] startup
[1.162s] [ext: omni.kit.helper.file_utils-0.1.7] startup
[1.163s] [ext: omni.kit.widget.path_field-2.0.9] startup
[1.163s] [ext: omni.kit.search_core-1.0.5] startup
[1.164s] [ext: omni.kit.widget.filebrowser-2.3.47] startup
[1.167s] [ext: omni.kit.widget.browser_bar-2.0.9] startup
[1.167s] [ext: omni.kit.widget.context_menu-1.2.1] startup
[1.168s] [ext: omni.kit.widget.search_delegate-1.0.4] startup
[1.168s] [ext: omni.kit.notification_manager-1.0.8] startup
[1.170s] [ext: omni.kit.clipboard-1.0.3] startup
[1.170s] [ext: omni.kit.usd.layers-2.1.30] startup
[1.177s] [ext: omni.kit.menu.utils-1.5.23] startup
[1.185s] [ext: omni.kit.window.filepicker-2.10.32] startup
[1.193s] [ext: omni.kit.stage_template.core-1.1.20] startup
[1.193s] [ext: omni.kit.primitive.mesh-1.0.16] startup
[1.195s] [ext: omni.kit.window.file_importer-1.1.11] startup
[1.197s] [ext: omni.kit.window.file_exporter-1.0.29] startup
[1.197s] [ext: omni.kit.stage_templates-1.2.2] startup
[1.198s] [ext: omni.kit.collaboration.presence_layer-1.0.8] startup
[1.200s] [ext: omni.kit.window.file-1.3.52] startup
[1.202s] [ext: omni.kit.context_menu-1.8.0] startup
[1.202s] [ext: omni.mdl-52.0.1] startup
[1.214s] [ext: omni.kit.widget.searchable_combobox-1.0.5] startup
[1.215s] [ext: omni.hydra.engine.stats-1.0.1] startup
[1.218s] [ext: omni.kit.raycast.query-1.0.5] startup
[1.226s] [ext: omni.kit.material.library-1.4.0] startup
[1.228s] [ext: omni.kit.widget.settings-1.1.0] startup
[1.229s] [ext: omni.kit.widget.prompt-1.0.7] startup
[1.230s] [ext: omni.kit.viewport.window-106.0.8] startup
[1.240s] [ext: omni.kit.window.preferences-1.5.1] startup
[1.247s] [ext: omni.kit.widget.live_session_management.ui-1.0.1] startup
[1.249s] [ext: omni.kit.viewport.utility-1.0.17] startup
[1.249s] [ext: omni.kit.widget.live_session_management-1.2.18] startup
[1.250s] [ext: omni.convexdecomposition-106.0.16] startup
[1.254s] [ext: omni.kit.hotkeys.core-1.3.3] startup
[1.255s] [ext: omni.kit.window.content_browser_registry-0.0.4] startup
[1.255s] [ext: omni.kit.widget.filter-1.1.3] startup
[1.255s] [ext: omni.kit.widget.searchfield-1.1.5] startup
[1.256s] [ext: omni.kit.widget.highlight_label-1.0.1] startup
[1.256s] [ext: omni.kit.window.content_browser-2.9.13] startup
[1.265s] [ext: omni.kit.window.property-1.11.1] startup
[1.266s] [ext: omni.kit.widget.stage-2.10.26] startup
[1.272s] [ext: omni.kit.widget.text_editor-1.0.2] startup
[1.273s] [ext: omni.kit.property.usd-3.21.26] startup
[1.279s] [ext: omni.kvdb-106.0.16] startup
[1.280s] [ext: omni.physx.foundation-106.0.16] startup
[1.280s] [ext: omni.localcache-106.0.16] startup
[1.281s] [ext: omni.inspect-1.0.1] startup
[1.282s] [ext: omni.kit.widget.graph-1.12.6] startup
[1.285s] [ext: omni.graph.tools-1.77.0] startup
[1.297s] [ext: omni.graph.core-2.170.0] startup
[1.300s] [ext: omni.usdphysics-106.0.16] startup
[1.303s] [ext: omni.kit.window.extensions-1.4.7] startup
[1.307s] [ext: omni.graph-1.135.0] startup
[1.390s] [ext: omni.physx.cooking-106.0.16] startup
[1.406s] [ext: omni.graph.ui-1.67.1] startup
[1.431s] [ext: omni.graph.action_core-1.1.4] startup
[1.439s] [ext: omni.physx-106.0.16] startup
[1.452s] [ext: omni.graph.action_nodes-1.21.3] startup
[1.460s] [ext: omni.kit.numpy.common-0.1.2] startup
[1.462s] [ext: omni.kit.manipulator.camera-105.0.5] startup
[1.466s] [ext: omni.physx.stageupdate-106.0.16] startup
[1.470s] [ext: omni.graph.action-1.101.1] startup
[1.471s] [ext: omni.isaac.kit-1.10.0] startup
[1.473s] [ext: omni.isaac.dynamic_control-1.3.7] startup
[1.480s] [ext: omni.kit.graph.delegate.default-1.2.2] startup
[1.482s] [ext: omni.physics.tensors-106.0.16] startup
[1.494s] [ext: omni.isaac.version-1.1.0] startup
[1.496s] [ext: omni.physx.tensors-106.0.16] startup
[1.502s] [ext: omni.warp.core-1.1.0] startup
Warp 1.1.0 initialized:
   CUDA Toolkit 11.5, Driver 12.3
   Devices:
     "cpu"      : "x86_64"
     "cuda:0"   : "NVIDIA GeForce RTX 4080 Laptop GPU" (12 GiB, sm_89, mempool enabled)
   Kernel cache:
     /home/param/.cache/warp/1.1.0
[1.570s] [ext: omni.isaac.nucleus-0.1.2] startup
[1.570s] [ext: omni.kit.graph.delegate.modern-1.10.6] startup
[1.573s] [ext: omni.isaac.core-3.12.0] startup
[2.338s] [ext: omni.kit.graph.editor.core-1.5.3] startup
[2.341s] [ext: omni.kit.manipulator.viewport-107.0.0] startup
[2.342s] [ext: omni.kit.graph.widget.variables-2.1.0] startup
[2.344s] [ext: omni.kit.graph.usd.commands-1.3.1] startup
[2.345s] [ext: omni.graph.visualization.nodes-2.1.1] startup
[2.350s] [ext: omni.graph.window.core-1.107.1] startup
[2.360s] [ext: omni.ui_query-1.1.2] startup
[2.362s] [ext: omni.graph.window.generic-1.23.1] startup
[2.366s] [ext: omni.kit.ui_test-1.2.18] startup
[2.367s] [ext: omni.kit.ui.actions-1.0.1] startup
[2.368s] [ext: omni.isaac.ui-0.15.1] startup
[2.370s] [ext: omni.kit.window.cursor-1.1.2] startup
[2.372s] [ext: omni.kit.menu.common-1.1.5] startup
[2.374s] [ext: omni.command.usd-1.0.3] startup
[2.375s] [ext: omni.isaac.menu-0.4.1] startup
[2.376s] [ext: omni.kit.viewport.menubar.core-107.0.0] startup
[2.385s] [ext: omni.kit.viewport.actions-105.2.8] startup
[2.389s] [ext: omni.graph.window.action-1.25.2] startup
[2.394s] [ext: omni.kit.viewport.menubar.display-106.0.0] startup
[2.396s] [ext: omni.debugdraw-0.1.3] startup
[2.400s] [ext: omni.kit.widget.toolbar-1.6.2] startup
[2.405s] [ext: omni.kit.manipulator.transform-104.7.5] startup
[2.406s] [ext: omni.usdphysics.ui-106.0.16] startup
[2.426s] [ext: omni.physx.commands-106.0.16] startup
[2.429s] [ext: omni.kit.manipulator.tool.snap-1.4.5] startup
[2.432s] [ext: omni.kit.manipulator.selector-1.1.1] startup
[2.434s] [ext: omni.physx.ui-106.0.16] startup
[2.454s] [ext: omni.kit.property.material-1.9.3] startup
[2.457s] [ext: omni.kit.viewport.manipulator.transform-106.0.0] startup
ViewportTransformManipulatorExt on_startup
[2.457s] [ext: omni.physx.demos-106.0.16] startup
[2.470s] [ext: omni.kit.property.physx-106.0.16] startup
[2.520s] [ext: omni.kit.manipulator.prim.core-106.0.2] startup
[2.524s] [ext: omni.fabric.commands-1.1.4] startup
[2.528s] [ext: omni.graph.image.core-0.3.2] startup
[2.532s] [ext: omni.physx.vehicle-106.0.16] startup
[2.542s] [ext: omni.kit.manipulator.prim.usd-106.0.1] startup
[2.544s] [ext: omni.kit.manipulator.prim.fabric-106.0.1] startup
[2.545s] [ext: omni.graph.image.nodes-1.0.2] startup
[2.546s] [ext: omni.physx.camera-106.0.16] startup
[2.553s] [ext: omni.kit.manipulator.prim-106.0.0] startup
[2.553s] [ext: omni.graph.nodes-1.141.2] startup
[2.560s] [ext: omni.graph.ui_nodes-1.24.1] startup
[2.565s] [ext: omni.kit.manipulator.selection-104.0.9] startup
[2.567s] [ext: omni.kit.widget.layers-1.7.9] startup
[2.591s] [ext: omni.kit.window.toolbar-1.6.1] startup
[2.593s] [ext: omni.graph.scriptnode-1.18.2] startup
[2.595s] [ext: omni.graph.bundle.action-2.0.4] startup
[2.596s] [ext: omni.physx.cct-106.0.16] startup
[2.613s] [ext: omni.physx.graph-106.0.16] startup
[2.633s] [ext: omni.physx.supportui-106.0.16] startup
[2.663s] [ext: omni.physx.telemetry-106.0.16] startup
[2.667s] [ext: omni.kit.widget.material_preview-1.0.16] startup
[2.669s] [ext: omni.sensors.tiled-0.0.3] startup
[2.672s] [ext: omni.syntheticdata-0.6.7] startup
[2.694s] [ext: omni.warp-1.1.0] startup
[2.710s] [ext: omni.physx.bundle-106.0.16] startup
[2.710s] [ext: omni.kit.window.material_graph-1.8.15] startup
[2.779s] [ext: omni.isaac.debug_draw-0.7.1] startup
[2.812s] [ext: omni.sensors.nv.common-1.0.1] startup
[2.842s] [ext: omni.replicator.core-1.11.8] startup
2024-07-07 23:32:14 [2,845ms] [Warning] [omni.replicator.core.scripts.annotators] Annotator PostProcessDispatch is already registered, overwriting annotator template
[2.930s] [ext: omni.kit.menu.create-1.0.12] startup
[2.933s] [ext: omni.sensors.nv.materials-1.0.0] startup
[2.935s] [ext: omni.isaac.range_sensor-3.0.1] startup
[2.959s] [ext: omni.isaac.core_nodes-1.15.4] startup
[2.976s] [ext: omni.sensors.nv.wpm-1.0.0] startup
[2.978s] [ext: omni.kit.actions.window-1.1.1] startup
[2.983s] [ext: omni.kit.selection-0.1.4] startup
[2.985s] [ext: omni.sensors.nv.radar-1.0.1] startup
[2.990s] [ext: omni.sensors.nv.lidar-1.0.1] startup
[2.995s] [ext: omni.kit.menu.file-1.1.9] startup
[3.000s] [ext: omni.kit.menu.edit-1.1.19] startup
[3.009s] [ext: omni.isaac.sensor-11.3.0] startup
[3.082s] [ext: omni.kit.hotkeys.window-1.4.5] startup
[3.092s] [ext: omni.kit.property.isaac-0.2.3] startup
[3.099s] [ext: omni.kit.property.layer-1.1.5] startup
[3.102s] [ext: omni.kit.stage_column.payload-2.0.0] startup
[3.106s] [ext: omni.kit.stage_column.variant-1.0.13] startup
[3.111s] [ext: omni.kit.stagerecorder.core-105.0.5] startup
[3.115s] [ext: omni.rtx.window.settings-0.6.15] startup
[3.118s] [ext: omni.kit.widget.live-2.1.6] startup
[3.120s] [ext: omni.kit.viewport.menubar.camera-105.1.8] startup
[3.124s] [ext: omni.kit.viewport.menubar.render-106.1.2] startup
[3.126s] [ext: omni.kit.viewport.menubar.settings-106.0.0] startup
[3.129s] [ext: omni.kit.viewport.rtx-104.0.1] startup
[3.129s] [ext: omni.kit.widget.cache_indicator-2.0.8] startup
[3.159s] [ext: omni.kit.property.audio-1.0.11] startup
[3.162s] [ext: omni.kit.widget.calendar-1.0.8] startup
2024-07-07 23:32:14 [3,148ms] [Warning] [omni.kit.widget.cache_indicator.cache_state_menu] Unable to detect Omniverse Cache Server. Consider installing it for better IO performance.
[3.164s] [ext: omni.kit.widget.stage_icons-1.0.3] startup
[3.165s] [ext: omni.hydra.scene_api-0.1.2] startup
[3.172s] [ext: omni.kit.property.geometry-1.3.0] startup
[3.175s] [ext: omni.kit.property.camera-1.0.6] startup
[3.177s] [ext: omni.kit.widget.extended_searchfield-1.0.27] startup
[3.182s] [ext: omni.kit.window.stage-2.5.9] startup
[3.186s] [ext: omni.kit.property.transform-1.5.1] startup
[3.189s] [ext: omni.kit.property.render-1.1.1] startup
[3.190s] [ext: omni.kit.property.light-1.0.8] startup
[3.192s] [ext: omni.kit.window.commands-0.2.5] startup
[3.193s] [ext: omni.kit.widget.timeline-105.0.1] startup
[3.194s] [ext: omni.kit.menu.stage-1.2.5] startup
[3.196s] [ext: omni.kit.property.bundle-1.2.11] startup
[3.197s] [ext: omni.kit.window.status_bar-0.1.6] startup
[3.201s] [ext: omni.kit.window.title-1.1.3] startup
[3.201s] [ext: omni.replicator.isaac-1.15.0] startup
[3.210s] [ext: omni.replicator.replicator_yaml-2.0.5] startup
[3.232s] [ext: omni.rtx.settings.core-0.6.0] startup
[3.238s] [ext: omni.kit.window.console-0.2.12] startup
[3.247s] [ext: semantics.schema.editor-0.3.4] startup
[3.252s] [ext: semantics.schema.property-1.0.2] startup
[3.254s] [ext: omni.kit.window.script_editor-1.7.6] startup
[3.257s] [ext: omni.kit.profiler.window-2.2.1] startup
2024-07-07 23:32:14 [3,245ms] [Warning] [omni.kit.profiler.window] remove _SpanInstance.__lt__ and use insort 'key' arg instead
[3.352s] [ext: omni.isaac.utils-1.0.1] startup
[3.356s] [ext: omni.isaac.cloner-0.8.1] startup
[3.357s] [ext: omni.kit.window.stats-0.1.6] startup
[3.360s] [ext: isaaclab.python-1.0.0] startup
[3.361s] Simulation App Starting
[4.891s] app ready
[5.808s] Simulation App Startup Complete
[5.810s] Failed to solve some dependencies locally, syncing with extension registry...
[5.817s] [ext: omni.kit.registry.nucleus-0.0.0] startup
2024-07-07 23:32:19 [7,553ms] [Error] [omni.ext.plugin] Failed to resolve extension dependencies. Failure hints:
	Can't find extension with name: omni.isaac.ros2_bridge
 Available versions:
	 (none found)
 Synced registries:
	 - kit/default         : found 476 packages 
	 - kit/sdk             : found 471 packages 
	 - kit/community       : found 350 packages 

Traceback (most recent call last):
  File "/home/param/go2_omniverse/main.py", line 32, in <module>
    run_sim()
  File "/home/param/go2_omniverse/omniverse_sim.py", line 181, in run_sim
    create_front_cam_omnigraph(i)
  File "/home/param/go2_omniverse/omnigraph.py", line 35, in create_front_cam_omnigraph
    og.Controller.edit(
  File "/home/param/anaconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/extscache/omni.graph/omni/graph/core/_impl/controller.py", line 1171, in edit
    return obj.__edit(obj, args=args, kwargs=kwargs)
  File "/home/param/anaconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/extscache/omni.graph/omni/graph/core/_impl/controller.py", line 1372, in __edit
    return __do_the_edits()
  File "/home/param/anaconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/extscache/omni.graph/omni/graph/core/_impl/controller.py", line 1288, in __do_the_edits
    nodes_constructed = obj._process_create_nodes(  # noqa: PLW0212
  File "/home/param/anaconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/extscache/omni.graph/omni/graph/core/_impl/controller.py", line 512, in _process_create_nodes
    nodes_constructed = [
  File "/home/param/anaconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/extscache/omni.graph/omni/graph/core/_impl/controller.py", line 513, in <listcomp>
    obj.create_node(
  File "/home/param/anaconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/extscache/omni.graph/omni/graph/core/_impl/graph_controller.py", line 225, in create_node
    return obj.__create_node(obj, args=args, kwargs=kwargs)
  File "/home/param/anaconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/extscache/omni.graph/omni/graph/core/_impl/graph_controller.py", line 307, in __create_node
    raise og.OmniGraphError(f"Could not create node using unrecognized type '{node_type_id}'{more}")
omni.graph.core._impl.errors.OmniGraphError: OmniGraphError: Could not create node using unrecognized type 'omni.isaac.ros2_bridge.ROS2CameraHelper'. Perhaps the extension 'omni.isaac.ros2_bridge' is not loaded?
2024-07-07 23:32:19 [8,326ms] [Warning] [carb] [Plugin: omni.sensors.tiled.plugin] Module /home/param/anaconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/extscache/omni.sensors.tiled-0.0.3+106.0.0.lx64.r/bin/libomni.sensors.tiled.plugin.so remained loaded after unload request
2024-07-07 23:32:19 [8,330ms] [Warning] [carb] [Plugin: omni.spectree.delegate.plugin] Module /home/param/anaconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/extscache/omni.usd_resolver/bin/libomni.spectree.delegate.plugin.so remained loaded after unload request
2024-07-07 23:32:19 [8,332ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-07-07 23:32:19 [8,332ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-07-07 23:32:19 [8,332ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-07-07 23:32:19 [8,332ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-07-07 23:32:19 [8,332ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-07-07 23:32:19 [8,332ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-07-07 23:32:19 [8,332ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-07-07 23:32:19 [8,332ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-07-07 23:32:19 [8,332ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-07-07 23:32:19 [8,332ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-07-07 23:32:19 [8,332ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-07-07 23:32:19 [8,332ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Core' for removal
2024-07-07 23:32:19 [8,417ms] [Warning] [carb] Recursive unloadAllPlugins() detected!

**Comment by abizovnuralem** [comment]
Did you happen to activate env before launching the script? You shouldn't do it

**Comment by paramoza999** [comment]
> Did you happen to activate env before launching the script? You shouldn't do it

No, i directly launched the shell script

**Comment by ahanjaya** [comment]
I also faced the same issue, the problem is like this. I didn't activate the isaaclab env before launching the script.
```
2024-07-29 01:56:16 [10,958ms] [Error] [omni.ext.plugin] Failed to resolve extension dependencies. Failure hints:
	Can't find extension with name: omni.isaac.ros2_bridge
 Available versions:
	 (none found)
 Synced registries:
	 - kit/default         : found 477 packages 
	 - kit/sdk             : found 471 packages 
	 - kit/community       : found 362 packages 
```

**Comment by ahanjaya** [comment]
Solve by installing `isaacsim-ros2`

```bash
conda activate isaaclab
pip install isaacsim-ros2 --extra-index-url https://pypi.nvidia.com
```

**Comment by abizovnuralem** [comment]
Can you tell me the version of Isaac sim nd nvidia omniverse, please? I will double check on my side @paramoza999

**Comment by paramoza999** [comment]
I am using Isaac 4.0 and ros2 humble
