### ISSUE TITLE
Unable to run Go2, G1 runs fine

### ISSUE THREAD

**Issue by fabioscap** [abizovnuralem/go2_omniverse#23]
Hi,
I am having problems running your code for the go2 simulation in Isaac. I can run the other simulation with the humanoid.
Here are the error messages I get when I run run_sim.sh

**Some warnings about meshes:**
2024-08-13 14:37:22 [14,742ms] [Warning] [omni.replicator.core.scripts.utils.utils] Encountered invalid prim path /World/envs/env_0/Robot/base/front_cam
2024-08-13 14:37:22 [14,746ms] [Warning] [omni.fabric.plugin] No source has valid data array=0x1f54dba0 usdValid=0 cpuValid=0
2024-08-13 14:37:22 [14,746ms] [Warning] [omni.replicator.core.scripts.utils.utils] Encountered invalid prim path /World/envs/env_1/Robot/base/front_cam
[...]
2024-08-13 14:37:24 [15,975ms] [Warning] [omni.hydra] Mesh '/World/envs/env_0/Robot/base/visuals.proto_mesh_0_id0' has corrupted data in primvar 'st': buffer size 178533 doesn't match expected size 233784 in faceVarying primvars

**Some python errors:**
Exception ignored in: <function Camera.__del__ at 0x7a14653175b0>
Traceback (most recent call last):
  File "/home/fabioscap/Desktop/go2_omniverse/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sensors/camera/camera.py", line 139, in __del__
    for _, annotators in self._rep_registry.items():
AttributeError: 'Camera' object has no attribute '_rep_registry'
Traceback (most recent call last):
  File "/home/fabioscap/Desktop/go2_omniverse/go2_omniverse/main.py", line 29, in <module>
    run_sim()
  File "/home/fabioscap/Desktop/go2_omniverse/go2_omniverse/omniverse_sim.py", line 219, in run_sim
    add_camera(env_cfg.scene.num_envs, args_cli.robot)
  File "/home/fabioscap/Desktop/go2_omniverse/go2_omniverse/ros2.py", line 113, in add_camera
    Camera(cameraCfg)
  File "/home/fabioscap/Desktop/go2_omniverse/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sensors/camera/camera.py", line 121, in __init__
    self.cfg.spawn.func(
  File "/home/fabioscap/Desktop/go2_omniverse/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sim/utils.py", line 245, in wrapper
    prim = func(prim_paths[0], cfg, *args, **kwargs)
  File "/home/fabioscap/Desktop/go2_omniverse/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sim/spawners/sensors/sensors.py", line 86, in spawn_camera
    raise ValueError(f"A prim already exists at path: '{prim_path}'.")
ValueError: A prim already exists at path: '/World/envs/env_1/Robot/base/front_cam'.

Are you able to tell me if you are using a specific checkout of IsaacLab? Or do you know what could be the sources of these errors? thanks for the good work :v:

**Comment by abizovnuralem** [comment]
Can you try one more time with --robot_amount 1 please?

**Comment by fabioscap** [comment]
decreasing the robot amount to 1 makes it run, thanks! :sunglasses:

**Comment by abizovnuralem** [comment]
In case if you have a powerful GPU you can run multiple GO2 simultaneously, but if you don't you will have some issues with it.
