### ISSUE TITLE
omniverse-sim.py CPU pipeline argument error -- fix

### ISSUE THREAD

**Issue by PetriJF** [abizovnuralem/go2_omniverse#26]
Hello everyone,

Running environment:
- Ubuntu 22.04
- ROS2 Humble
- IsaacSim 4.1.0
- IsaacLab commit: 0b4f7bd

When running the repository for the GO2 script, the following happens:
``` bash
james@workstation:~/unitree_resources/go2_omniverse$ ./run_sim.sh 
#All required rosdeps installed successfully
Starting >>> carter_navigation
Starting >>> custom_message
Starting >>> isaac_ros2_messages
Starting >>> isaac_ros_navigation_goal
Starting >>> isaac_tutorials
Finished <<< carter_navigation [0.18s]                                                                                                 
Finished <<< isaac_tutorials [0.18s]
Finished <<< custom_message [0.29s]                                                                                                            
Finished <<< isaac_ros2_messages [0.29s]
Finished <<< isaac_ros_navigation_goal [0.41s]          

Summary: 5 packages finished [0.53s]
#All required rosdeps installed successfully
Starting >>> go2_interfaces
Finished <<< go2_interfaces [0.38s]                     

Summary: 1 package finished [0.50s]
Traceback (most recent call last):
  File "/home/james/unitree_resources/go2_omniverse/main.py", line 25, in <module>
    from omniverse_sim import run_sim
  File "/home/james/unitree_resources/go2_omniverse/omniverse_sim.py", line 35, in <module>
    AppLauncher.add_app_launcher_args(parser)
  File "/home/james/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/app/app_launcher.py", line 253, in add_app_launcher_args
    arg_group.add_argument("--cpu", action="store_true", help=argparse.SUPPRESS)
  File "/home/james/miniconda3/envs/isaaclab/lib/python3.10/argparse.py", line 1448, in add_argument
    return self._add_action(action)
  File "/home/james/miniconda3/envs/isaaclab/lib/python3.10/argparse.py", line 1650, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/home/james/miniconda3/envs/isaaclab/lib/python3.10/argparse.py", line 1462, in _add_action
    self._check_conflict(action)
  File "/home/james/miniconda3/envs/isaaclab/lib/python3.10/argparse.py", line 1599, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/home/james/miniconda3/envs/isaaclab/lib/python3.10/argparse.py", line 1608, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --cpu: conflicting option string: --cpu
```

I am aware that the repo works for IsaacSim 4.0, and me using 4.1 might be the cause for this.
Nevertheless, there is a simple fix for anyone encountering it: LN18 in `omniverse_sim.py` change `--cpu` to something like '--cpu-pipeline'.

This will fix the argument conflict.

**Comment by abizovnuralem** [comment]
@PetriJF Hello! Thanks for your help, I tested it with 4.1 and saw a significant drop in simulation speed (the dog is like a Neo from the Matrix), What about you? Also, I cannot start more than 1 dog in the sim with 4.1, looks tile 4.0 and 4.1 has many difference..

**Comment by abizovnuralem** [comment]
@PetriJF Hello! I have a solution for the speed drop, can you please check it? https://github.com/abizovnuralem/go2_omniverse/issues/30

**Comment by PetriJF** [comment]
Hey @abizovnuralem 

I will take a look tomorrow when I get into the office!
Will let you know
