### ISSUE TITLE
Collision Support

### ISSUE THREAD

**Issue by ShaoshuSu** [abizovnuralem/go2_omniverse#33]
Hi there,

I noticed that when I load the office environment, there seems to be no physical collision detection. Do you have any idea how to incorporate the physical property in the simulation environment?

Thanks a lot in advance!

[Screencast from 09-02-2024 10:33:11 PM.webm](https://github.com/user-attachments/assets/2daaaf30-d219-43f5-bf89-1fad7ad29284)

**Comment by ShaoshuSu** [comment]
nvm, I just solved it by adding the physical property with the collider preset.

![image](https://github.com/user-attachments/assets/66399cb0-ccca-4e3f-966b-cf66a7b72234)

By the way, when I add that property in USD Composer, save and download it, and then load it into the environment, I encounter the following error. Do you might know why this is happening?

```
2024-09-03 03:57:10 [33,215ms] [Warning] [omni.physx.plugin] PhysicsUSD: Parse collision - triangle mesh collision (approximation None/MeshSimplification) without SDF cannot be a part of a dynamic body, falling back to convexHull approximation: /World/office2/Salon/Salon_Downcabinet. To enable SDF collisions, sdfResolution should be > 0.
2024-09-03 03:57:10 [33,398ms] [Error] [omni.physx.tensors.plugin] CUDA error: an illegal memory access was encountered: ../../../extensions/runtime/source/omni.physx.tensors/plugins/gpu/GpuRigidContactView.cpp: 222
Traceback (most recent call last):
  File "/home/shaoshu/research/isaac/go2_omniverse_2023_1_1/main.py", line 29, in <module>
    run_sim()
  File "/home/shaoshu/research/isaac/go2_omniverse_2023_1_1/omniverse_sim.py", line 258, in run_sim
    obs, _, _, _ = env.step(actions)
  File "/home/shaoshu/research/isaac/IsaacLab-0.3.1/source/extensions/omni.isaac.orbit_tasks/omni/isaac/orbit_tasks/utils/wrappers/rsl_rl/vecenv_wrapper.py", line 160, in step
    obs_dict, rew, terminated, truncated, extras = self.env.step(actions)
  File "/home/shaoshu/.conda/envs/orbit/lib/python3.10/site-packages/gymnasium/wrappers/order_enforcing.py", line 56, in step
    return self.env.step(action)
  File "/home/shaoshu/research/isaac/IsaacLab-0.3.1/source/extensions/omni.isaac.orbit/omni/isaac/orbit/envs/rl_task_env.py", line 175, in step
    self.scene.update(dt=self.physics_dt)
  File "/home/shaoshu/research/isaac/IsaacLab-0.3.1/source/extensions/omni.isaac.orbit/omni/isaac/orbit/scene/interactive_scene.py", line 276, in update
    sensor.update(dt, force_recompute=not self.cfg.lazy_sensor_update)
  File "/home/shaoshu/research/isaac/IsaacLab-0.3.1/source/extensions/omni.isaac.orbit/omni/isaac/orbit/sensors/sensor_base.py", line 195, in update
    self._update_outdated_buffers()
  File "/home/shaoshu/research/isaac/IsaacLab-0.3.1/source/extensions/omni.isaac.orbit/omni/isaac/orbit/sensors/sensor_base.py", line 279, in _update_outdated_buffers
    self._update_buffers_impl(outdated_env_ids)
  File "/home/shaoshu/research/isaac/IsaacLab-0.3.1/source/extensions/omni.isaac.orbit/omni/isaac/orbit/sensors/contact_sensor/contact_sensor.py", line 310, in _update_buffers_impl
    self._data.net_forces_w[env_ids, :, :] = net_forces_w.view(-1, self._num_bodies, 3)[env_ids]
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by abizovnuralem** [comment]
Currently, I do not have any idea why PhyX is crashing with USD + collisions. The only way that I know is to download USD and manually put them with colliders.

**Comment by abizovnuralem** [comment]
This error log indicates several issues occurring in an Omniverse/Isaac Sim environment. Let's break down the problem and provide some suggestions:

Warning about collision mesh:
The first warning suggests that a triangle mesh collision for a dynamic body (likely part of the environment) is falling back to a convex hull approximation. This isn't causing the crash, but it might affect simulation accuracy.
CUDA error:
The main issue is a CUDA error indicating an illegal memory access. This is likely causing the simulation to crash.
Traceback:
The error occurs during the env.step() call in the simulation loop, specifically when updating sensor data.

To address these issues:

For the collision mesh warning:

Consider enabling SDF (Signed Distance Field) collisions by setting sdfResolution > 0 for the problematic object ("/World/office2/Salon/Salon_Downcabinet").


For the CUDA error:

Ensure your CUDA drivers and PyTorch version are compatible and up-to-date.
Check if you're running out of GPU memory. You might need to reduce the complexity of your simulation or use a GPU with more memory.
As suggested in the error message, you can try running with CUDA_LAUNCH_BLOCKING=1 to get more synchronous error reporting, which might provide more details about the exact location of the memory access issue.


For debugging:

Use CUDA_LAUNCH_BLOCKING=1 as mentioned above.
Consider compiling PyTorch with TORCH_USE_CUDA_DSA to enable device-side assertions, which can provide more detailed error information.
Review your sensor setup, particularly the contact sensor. There might be an issue with how the sensor data is being processed or accessed.


General steps:

Double-check your environment setup, ensuring all dependencies are correctly installed and compatible.
Verify that your GPU supports the operations you're trying to perform.
If possible, try running a simpler version of your simulation to isolate the issue.



If these steps don't resolve the issue, you may need to dig deeper into your simulation code, particularly around how you're handling sensor data and CUDA operations. Consider reaching out to the Omniverse/Isaac Sim community or support channels for more specific assistance, as they might have encountered similar issues before.

**Comment by ShaoshuSu** [comment]
Thank you, it works!

**Comment by abizovnuralem** [comment]
@ShaoshuSu Can you tell me please, what helped you to fix it? Can you write some detailed instruction

**Comment by ShaoshuSu** [comment]
@abizovnuralem Sure! 

I changed the **Consider Approximation** from Triangle Mesh to SDF Mesh in the Physics Property. And it solves all issues including the CUDA problem. I guess that CUDA issue might be a compounded issue with that collision type issue?

![image](https://github.com/user-attachments/assets/7ef40d8c-57e5-45f3-9945-0ae63e024034)

**Comment by abizovnuralem** [comment]
> @abizovnuralem Sure!
> 
> I changed the **Consider Approximation** from `Triangle Mesh` to `SDF Mesh` in the Physics Property. And it solves all issues including the CUDA problem. I guess that the CUDA issue might be a compounded issue with that collision-type issue.
> 
> ![image](https://private-user-images.githubusercontent.com/100821008/364125273-7ef40d8c-57e5-45f3-9945-0ae63e024034.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDY1NTMsIm5iZiI6MTcyNTQ0NjI1MywicGF0aCI6Ii8xMDA4MjEwMDgvMzY0MTI1MjczLTdlZjQwZDhjLTU3ZTUtNDVmMy05OTQ1LTBhZTYzZTAyNDAzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxMDM3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDc4ZThlN2YyMjk1NTZkMDNlZWI2Nzc4MGRiMGU5ODcwOTE2YmFmNzkxOWFlNWZlMTVjZGI0NjJkYWExYzFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MJ_hhyL8B7rhU8TVVZsjY4U9gys71VeSkMi3fUFdoeE)

thanks!

**Comment by kajwang** [comment]
Hi, I also met this issue. Changing Approximation to SDF Mesh do solve the error when adding colliders.
But when I try adding rigid body to an object, this CUDA error shows up again. Do you have any ideas about that?

> nvm, I just solved it by adding the physical property with the collider preset.
> 
> ![image](https://private-user-images.githubusercontent.com/100821008/363836570-66399cb0-ccca-4e3f-966b-cf66a7b72234.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MzMwNTYsIm5iZiI6MTcyNTQzMjc1NiwicGF0aCI6Ii8xMDA4MjEwMDgvMzYzODM2NTcwLTY2Mzk5Y2IwLWNjY2EtNGUzZi05NjZiLWNmNjZhN2I3MjIzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQwNjUyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDAxMWUxODg2NDM1ZGIzYWFlNmFkNWY2ZjA5YjM2MjVkY2U4ZWUzNzRiN2FmNjljOTM5NDJlNTU5NThhYzBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qBoKF-bqFy4ToFHwiyjgp-r-ybrOdnzG24bmIeJ6J_4)
> 
> By the way, when I add that property in USD Composer, save and download it, and then load it into the environment, I encounter the following error. Do you might know why this is happening?
> 
> ```
> 2024-09-03 03:57:10 [33,215ms] [Warning] [omni.physx.plugin] PhysicsUSD: Parse collision - triangle mesh collision (approximation None/MeshSimplification) without SDF cannot be a part of a dynamic body, falling back to convexHull approximation: /World/office2/Salon/Salon_Downcabinet. To enable SDF collisions, sdfResolution should be > 0.
> 2024-09-03 03:57:10 [33,398ms] [Error] [omni.physx.tensors.plugin] CUDA error: an illegal memory access was encountered: ../../../extensions/runtime/source/omni.physx.tensors/plugins/gpu/GpuRigidContactView.cpp: 222
> Traceback (most recent call last):
>   File "/home/shaoshu/research/isaac/go2_omniverse_2023_1_1/main.py", line 29, in <module>
>     run_sim()
>   File "/home/shaoshu/research/isaac/go2_omniverse_2023_1_1/omniverse_sim.py", line 258, in run_sim
>     obs, _, _, _ = env.step(actions)
>   File "/home/shaoshu/research/isaac/IsaacLab-0.3.1/source/extensions/omni.isaac.orbit_tasks/omni/isaac/orbit_tasks/utils/wrappers/rsl_rl/vecenv_wrapper.py", line 160, in step
>     obs_dict, rew, terminated, truncated, extras = self.env.step(actions)
>   File "/home/shaoshu/.conda/envs/orbit/lib/python3.10/site-packages/gymnasium/wrappers/order_enforcing.py", line 56, in step
>     return self.env.step(action)
>   File "/home/shaoshu/research/isaac/IsaacLab-0.3.1/source/extensions/omni.isaac.orbit/omni/isaac/orbit/envs/rl_task_env.py", line 175, in step
>     self.scene.update(dt=self.physics_dt)
>   File "/home/shaoshu/research/isaac/IsaacLab-0.3.1/source/extensions/omni.isaac.orbit/omni/isaac/orbit/scene/interactive_scene.py", line 276, in update
>     sensor.update(dt, force_recompute=not self.cfg.lazy_sensor_update)
>   File "/home/shaoshu/research/isaac/IsaacLab-0.3.1/source/extensions/omni.isaac.orbit/omni/isaac/orbit/sensors/sensor_base.py", line 195, in update
>     self._update_outdated_buffers()
>   File "/home/shaoshu/research/isaac/IsaacLab-0.3.1/source/extensions/omni.isaac.orbit/omni/isaac/orbit/sensors/sensor_base.py", line 279, in _update_outdated_buffers
>     self._update_buffers_impl(outdated_env_ids)
>   File "/home/shaoshu/research/isaac/IsaacLab-0.3.1/source/extensions/omni.isaac.orbit/omni/isaac/orbit/sensors/contact_sensor/contact_sensor.py", line 310, in _update_buffers_impl
>     self._data.net_forces_w[env_ids, :, :] = net_forces_w.view(-1, self._num_bodies, 3)[env_ids]
> RuntimeError: CUDA error: an illegal memory access was encountered
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> ```

**Comment by brandon-lawrence96** [comment]
Hi @ShaoshuSu. Did you manage to solve the error for adding rigid bodies? Thank you.

**Comment by kajwang** [comment]
> Hi @ShaoshuSu and @kajwang. Did you manage to solve the error for adding rigid bodies? Thank you.

No did not manage to solve it, instead I avoided it by haulting self._data.net_forces_w update in code.
