### ISSUE TITLE
Required Isaac sim version not available

### ISSUE THREAD

**Issue by ronakhb** [abizovnuralem/go2_omniverse#45]
Hello,
As I was going through the setup steps, I noticed that Nvidia removed the option to install Isaac Sim below version 4.0
I cant seem to find any way to get the older version. The new version did not work with the specified orbit version. Please help with this issue

**Comment by abizovnuralem** [comment]
Hello, have you tried this https://github.com/abizovnuralem/go2_omniverse?tab=readme-ov-file#troubleshooting and this https://github.com/abizovnuralem/go2_omniverse/tree/added_copter?tab=readme-ov-file

**Comment by ronakhb** [comment]
Thanks for the prompt solution. I switched the branch and set up the added_copter branch. However, i am getting an error when I run the run.sh script

```
Traceback (most recent call last):
  File "/home/ronak/go2_omniverse/main.py", line 25, in <module>
    from omniverse_sim import run_sim
  File "/home/ronak/go2_omniverse/omniverse_sim.py", line 76, in <module>
    AppLauncher.add_app_launcher_args(parser)
  File "/home/ronak/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/app/app_launcher.py", line 220, in add_app_launcher_args
    AppLauncher._check_argparser_config_params(config)
  File "/home/ronak/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/app/app_launcher.py", line 354, in _check_argparser_config_params
    raise ValueError(
ValueError: The passed ArgParser object already has the field 'device'. This field will be added by `AppLauncher.add_app_launcher_args()`, and should not be added directly. Please remove the argument or rename it to a non-conflicting name.
```

**Comment by ronakhb** [comment]
Update, I was able to get rid of these errors by properly installing all dependencies again in the isaaclab environment. However I've hit a wall now with this error

`2024-10-03 22:25:36 [4,773ms] [Warning] [omni.kit.profiler.window] remove _SpanInstance.__lt__ and use insort 'key' arg instead
[4.789s] [ext: omni.isaac.utils-1.0.1] startup
[4.793s] [ext: omni.isaac.cloner-0.8.1] startup
[4.795s] [ext: omni.kit.window.stats-0.1.6] startup
[4.798s] [ext: isaaclab.python-1.2.0] startup
[4.800s] Simulation App Starting
[6.311s] app ready
[7.112s] Simulation App Startup Complete
[7.118s] [ext: omni.isaac.ros2_bridge-2.26.4] startup
[7.138s] Attempting to load system rclpy
[7.154s] rclpy loaded
: CommandLine Error: Option 'nvptx-no-f16-math' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
Aborted (core dumped)
`

**Comment by abizovnuralem** [comment]
Can you tell me all the information about our machine with Isaac's version on it, please?

**Comment by abizovnuralem** [comment]
If you still have an issue just reopen it, thanks!
