### ISSUE TITLE
Unable to Load ROS2 bridge extension

### ISSUE THREAD

**Issue by Jellal-17** [abizovnuralem/go2_omniverse#46]
Hello, 
I am trying to use this repository through the Isaaclab version, I have previously installed Isaaclab and am using it for another project already. So, I followed all the instructions in the readme but I'm encountering this error no matter what I do. 

2024-10-03 10:22:25 [16,294ms] [Error] [omni.ext.plugin] Failed to resolve extension dependencies. Failure hints:
	Can't find extension with name: omni.isaac.ros2_bridge
 Available versions:
	 (none found)
 Synced registries:
	 - kit/default         : found 485 packages 
	 - kit/sdk             : found 482 packages 
	 - kit/community       : found 384 packages 

Traceback (most recent call last):
  File "/media/skadimisetty/Storage/Sathvik/anaconda3/envs/isaaclab/go2_omniverse-0.1.0/main.py", line 29, in <module>
    run_sim()
  File "/media/skadimisetty/Storage/Sathvik/anaconda3/envs/isaaclab/go2_omniverse-0.1.0/omniverse_sim.py", line 185, in run_sim
    create_front_cam_omnigraph(i)
  File "/media/skadimisetty/Storage/Sathvik/anaconda3/envs/isaaclab/go2_omniverse-0.1.0/omnigraph.py", line 35, in create_front_cam_omnigraph
    og.Controller.edit(
  File "/media/skadimisetty/Storage/Sathvik/anaconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/extscache/omni.graph/omni/graph/core/_impl/controller.py", line 1171, in edit
    return obj.__edit(obj, args=args, kwargs=kwargs)
  File "/media/skadimisetty/Storage/Sathvik/anaconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/extscache/omni.graph/omni/graph/core/_impl/controller.py", line 1372, in __edit
    return __do_the_edits()
  File "/media/skadimisetty/Storage/Sathvik/anaconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/extscache/omni.graph/omni/graph/core/_impl/controller.py", line 1288, in __do_the_edits
    nodes_constructed = obj._process_create_nodes(  # noqa: PLW0212
  File "/media/skadimisetty/Storage/Sathvik/anaconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/extscache/omni.graph/omni/graph/core/_impl/controller.py", line 512, in _process_create_nodes
    nodes_constructed = [
  File "/media/skadimisetty/Storage/Sathvik/anaconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/extscache/omni.graph/omni/graph/core/_impl/controller.py", line 513, in <listcomp>
    obj.create_node(
  File "/media/skadimisetty/Storage/Sathvik/anaconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/extscache/omni.graph/omni/graph/core/_impl/graph_controller.py", line 225, in create_node
    return obj.__create_node(obj, args=args, kwargs=kwargs)
  File "/media/skadimisetty/Storage/Sathvik/anaconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/extscache/omni.graph/omni/graph/core/_impl/graph_controller.py", line 307, in __create_node
    raise og.OmniGraphError(f"Could not create node using unrecognized type '{node_type_id}'{more}")
omni.graph.core._impl.errors.OmniGraphError: OmniGraphError: Could not create node using unrecognized type 'omni.isaac.ros2_bridge.ROS2CameraHelper'. Perhaps the extension 'omni.isaac.ros2_bridge' is not loaded?

If I comment the following, though the app is loading, the extension seems to persist. 

"for i in range(env_cfg.scene.num_envs):
        create_front_cam_omnigraph(i)" 

Can anyone help me with this or did I do anything wrong while Installing it ?

**Comment by abizovnuralem** [comment]
Hello, it looks like an installation problem with venv, can you please double-check it with readme instructions?
