### ISSUE TITLE
ModuleNotFoundError: No module named 'omni.isaac.orbit'

### ISSUE THREAD

**Issue by sun900914** [abizovnuralem/go2_omniverse#51]
Hello,
I am trying to use this repository through Isaaclab. I installed Isaaclab and tested it. However, no matter what I do after following all the instructions in the readme, I encounter this error.

Failed   <<< go2_interfaces [0.24s, exited with code 1]
Summary: 0 packages finished [0.38s]
  1 package failed: go2_interfaces
  1 package had stderr output: go2_interfaces
Traceback (most recent call last):
  File "/home/t2503-3090/IsaacLab/go2_omniverse/main.py", line 25, in <module>
    from omniverse_sim import run_sim
  File "/home/t2503-3090/IsaacLab/go2_omniverse/omniverse_sim.py", line 7, in <module>
    from omni.isaac.orbit.app import AppLauncher
ModuleNotFoundError: No module named 'omni.isaac.orbit'

Below is my version
Ubuntu 22.04
isaac-sim 4.2.0
ros2-humble

Can anyone help me with this or did I do anything wrong while Installing it ?

**Comment by abizovnuralem** [comment]
Hello, currently the main branch supports only orbit, not osaacLab, but if you want to try isaaclab I have a copter branch so that you can try that code.

**Comment by abizovnuralem** [comment]
If you have additional questions, please open a new issue, thanks!

**Comment by Yandong-Luo** [comment]
I have meet the same situation. I think you can follow https://github.com/isaac-sim/IsaacLab/issues/103#issuecomment-1662112177 to fix it. I have successfully fixed it.
