### ISSUE TITLE
run_sim.sh crash on ubuntu 22.04 with isaacsim 4.2 on added_copter branch

### ISSUE THREAD

**Issue by haonan-duan** [abizovnuralem/go2_omniverse#55]
Hello, I am facing some errors when executing `run_sim.sh`:

Exception ignored in: <function Camera.__del__ at 0x779327de2cb0>
Traceback (most recent call last):
  File "/home/SENSETIME/duanhaonan/codes/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sensors/camera/camera.py", line 149, in __del__
    for _, annotators in self._rep_registry.items():
AttributeError: 'Camera' object has no attribute '_rep_registry'
Exception ignored in: <function Camera.__del__ at 0x779327de2cb0>
Traceback (most recent call last):
  File "/home/SENSETIME/duanhaonan/codes/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sensors/camera/camera.py", line 149, in __del__
    for _, annotators in self._rep_registry.items():
AttributeError: 'Camera' object has no attribute '_rep_registry'
Error loading custom environment. You should download custom envs folder from: https://drive.google.com/drive/folders/1vVGuO1KIX1K6mD6mBHDZGm9nk2vaRyj3?usp=sharing
2024-12-10 06:52:24 [12,861ms] [Warning] [lidar.lidarprofilereader] Member rotationDirection not found!
2024-12-10 06:52:24 [12,861ms] [Warning] [omni.sensors.nv.profile_reader.ext.plugin] This style of emitters will be deprecated in the near future. Use emitterStates approach instead.
2024-12-10 06:52:24 [12,955ms] [Warning] [rtx.rtxsensor.plugin] Using User-specified coordinate frame quaternion (0.000000, 0.000000, 0.000000, 1.000000) in RTXSensor
2024-12-10 06:52:24 [13,323ms] [Warning] [lidar.lidarprofilereader] Member rotationDirection not found!
2024-12-10 06:52:24 [13,323ms] [Warning] [omni.sensors.nv.profile_reader.ext.plugin] This style of emitters will be deprecated in the near future. Use emitterStates approach instead.
2024-12-10 06:52:24 [13,324ms] [Warning] [lidar.lidarprofilereader] Member rotationDirection not found!
2024-12-10 06:52:24 [13,325ms] [Warning] [omni.sensors.nv.profile_reader.ext.plugin] This style of emitters will be deprecated in the near future. Use emitterStates approach instead.
2024-12-10 06:52:24 [13,325ms] [Warning] [omni.isaac.sensor.plugin] IsaacComputeRTXLidarFlatScan: lowest elevation emitter line is 0.350000, not 0.
2024-12-10 06:52:24 [13,325ms] [Warning] [lidar.lidarprofilereader] Member rotationDirection not found!
2024-12-10 06:52:24 [13,325ms] [Warning] [omni.sensors.nv.profile_reader.ext.plugin] This style of emitters will be deprecated in the near future. Use emitterStates approach instead.
Traceback (most recent call last):
  File "/home/SENSETIME/duanhaonan/codes/go2_omniverse/main.py", line 29, in <module>
    run_sim()
  File "/home/SENSETIME/duanhaonan/codes/go2_omniverse/omniverse_sim.py", line 342, in run_sim
    pub_robo_data_ros2(
  File "/home/SENSETIME/duanhaonan/codes/go2_omniverse/ros2.py", line 151, in pub_robo_data_ros2
    env.env.scene["robot"].data.joint_names,
AttributeError: 'OrderEnforcing' object has no attribute 'scene'
2024-12-10 06:52:25 [13,444ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-10 06:52:25 [13,444ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-10 06:52:25 [13,444ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-10 06:52:25 [13,444ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-10 06:52:25 [13,444ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-10 06:52:25 [13,444ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-10 06:52:25 [13,444ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-10 06:52:25 [13,444ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-10 06:52:25 [13,444ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-10 06:52:25 [13,444ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-10 06:52:25 [13,444ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-10 06:52:25 [13,444ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-10 06:52:25 [13,444ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Core' for removal
2024-12-10 06:52:25 [13,578ms] [Warning] [carb] Recursive unloadAllPlugins() detected!

1. AttributeError: 'Camera' object has no attribute '_rep_registry'
2. I tried to put office.usd/warehouse.usd in `envs`, but the running will freeze without any response.
3. AttributeError: 'OrderEnforcing' object has no attribute 'scene'

Please help me for these, thank you!

**Comment by abizovnuralem** [comment]
Hello, can you please send me the PC configuration? Usually it takes 2-3 minutes for the first time

**Comment by babakc** [comment]
This fixed the OrderEnforcing problem for me: pip install "gymnasium==0.29.1"

Credit: https://forums.developer.nvidia.com/t/isaac-lab-multi-agent-skrl-documentation-not-working/316729
